version: "3.7"
services:
  feecc-cameraman:
    build:
      context: ./
      dockerfile: Dockerfile
    init: true
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - "./output:/output"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "~/.cache/pip/:/root/.cache/pip"
    environment:
      MONGODB_URI: ''  # Your MongoDB connection URI ending with /db-name
      PRODUCTION_ENVIRONMENT=: null  # Leave null if you want testing credentials to work
      CAMERAS_CONFIG: ''  # A json-like string for camera configuration (check README for more)
